jobs:
  include:
    - language: node_js
      node_js:
        - 12.11.0
      before_script:
        - cd services/frontend_service/app
        - yarn install
      script: yarn test

    - language: go
      go:
        - 1.13.x
      env:
        - GO111MODULE=on
      script: 
        - (cd services/auth_service && go test ./...)
        - (cd services/file_service && go test ./...)
        - (cd services/common/database && go test ./...)
        - (cd services/common/grpc_utils && go test ./...)
        - (cd services/common/logger && go test ./...)
        - (cd services/common/middleware && go test ./...)
        - (cd services/common/validation && go test ./...)
        - (cd services/frontend_service && go test ./...)
        - (cd services/post_service && go test ./...)
        - (cd services/user_service && go test ./...)

    - language: minimal
      services:
        - docker
      before_script:
        - cd deploy
      script: docker-compose -f production.yml build --parallel
