jobs:
  include:
    - language: node_js
      node_js:
        - 12.11.0
      before_script:
        - cd services/frontend_service/app
        - yarn install
      script: yarn test

    - language: go
      dist: 1.13.0
      before_script:
        - cd services
      script: 
        - go test ./...

    - language: minimal
      services:
        - docker
      before_script:
        - cd deploy
      script: docker-compose -f production.yml build --parallel
