version: '2'
services:
  frontend_service:
    image: frontend_service
    container_name: frontend_service
    restart: always
    build:
      context: ../services
      dockerfile: frontend_service/Dockerfile
    environment:
      - PORT=8000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=portal
      - AUTH_SVC_ADDR=auth_service:8001
      - USER_SVC_ADDR=user_service:8002
      - POST_SVC_ADDR=post_service:8003
      - FILE_SVC_ADDR=file_service:8004
      - JWT_SECRET
      - DB_USER
      - DB_PASSWORD
    ports:
      - 8000:8000

  auth_service:
    image: auth_service
    container_name: auth_service
    restart: always
    build:
      context: ../services
      dockerfile: auth_service/Dockerfile
    environment:
      - PORT=8001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=portal
      - DB_USER
      - DB_PASSWORD
    ports:
      - 8001:8001

  user_service:
    image: user_service
    container_name: user_service
    restart: always
    build:
      context: ../services
      dockerfile: user_service/Dockerfile
    environment:
      - PORT=8002
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=portal
      - DB_USER
      - DB_PASSWORD
    ports:
      - 8002:8002

  post_service:
    image: post_service
    container_name: post_service
    restart: always
    build:
      context: ../services
      dockerfile: post_service/Dockerfile
    environment:
      - PORT=8003
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=portal
      - DB_USER
      - DB_PASSWORD
    ports:
      - 8003:8003

  file_service:
    image: file_service
    container_name: file_service
    restart: always
    build:
      context: ../services
      dockerfile: file_service/Dockerfile
    environment:
      - PORT=8004
      - STORE_ADDR=minio:9000
      - STORE_BUCKET_NAME=portal
      - STORE_ACCESS_ID
      - STORE_SECRET_KEY
    ports:
      - 8004:8004

  mysql:
    image: mysql:8.0.17
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=portal
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  minio:
    image: minio/minio:RELEASE.2019-09-05T23-24-38Z
    container_name: minio
    restart: always
    command: server /data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    ports:
      - 80:80
      - 443:443

  nginx_letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - nginx

volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local