// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignInResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowerCount        uint32   `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	ProfilePicture       []byte   `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	PostCount            uint32   `protobuf:"varint,8,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *User) GetProfilePicture() []byte {
	if m != nil {
		return m.ProfilePicture
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *User) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetFollowersRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersRequest) Reset()         { *m = GetFollowersRequest{} }
func (m *GetFollowersRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowersRequest) ProtoMessage()    {}
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{6}
}

func (m *GetFollowersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersRequest.Unmarshal(m, b)
}
func (m *GetFollowersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersRequest.Merge(m, src)
}
func (m *GetFollowersRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowersRequest.Size(m)
}
func (m *GetFollowersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersRequest proto.InternalMessageInfo

func (m *GetFollowersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFollowersRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFollowersResponse struct {
	Followers            []*User  `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersResponse) Reset()         { *m = GetFollowersResponse{} }
func (m *GetFollowersResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowersResponse) ProtoMessage()    {}
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{7}
}

func (m *GetFollowersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersResponse.Unmarshal(m, b)
}
func (m *GetFollowersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersResponse.Merge(m, src)
}
func (m *GetFollowersResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowersResponse.Size(m)
}
func (m *GetFollowersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersResponse proto.InternalMessageInfo

func (m *GetFollowersResponse) GetFollowers() []*User {
	if m != nil {
		return m.Followers
	}
	return nil
}

type GetFollowingRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowingRequest) Reset()         { *m = GetFollowingRequest{} }
func (m *GetFollowingRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowingRequest) ProtoMessage()    {}
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{8}
}

func (m *GetFollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingRequest.Unmarshal(m, b)
}
func (m *GetFollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingRequest.Merge(m, src)
}
func (m *GetFollowingRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowingRequest.Size(m)
}
func (m *GetFollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingRequest proto.InternalMessageInfo

func (m *GetFollowingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFollowingRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFollowingResponse struct {
	Following            []*User  `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowingResponse) Reset()         { *m = GetFollowingResponse{} }
func (m *GetFollowingResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowingResponse) ProtoMessage()    {}
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{9}
}

func (m *GetFollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingResponse.Unmarshal(m, b)
}
func (m *GetFollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingResponse.Merge(m, src)
}
func (m *GetFollowingResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowingResponse.Size(m)
}
func (m *GetFollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingResponse proto.InternalMessageInfo

func (m *GetFollowingResponse) GetFollowing() []*User {
	if m != nil {
		return m.Following
	}
	return nil
}

type CreateFollowRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowId             string   `protobuf:"bytes,2,opt,name=follow_id,json=followId,proto3" json:"follow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFollowRequest) Reset()         { *m = CreateFollowRequest{} }
func (m *CreateFollowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFollowRequest) ProtoMessage()    {}
func (*CreateFollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{10}
}

func (m *CreateFollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFollowRequest.Unmarshal(m, b)
}
func (m *CreateFollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFollowRequest.Marshal(b, m, deterministic)
}
func (m *CreateFollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFollowRequest.Merge(m, src)
}
func (m *CreateFollowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFollowRequest.Size(m)
}
func (m *CreateFollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFollowRequest proto.InternalMessageInfo

func (m *CreateFollowRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateFollowRequest) GetFollowId() string {
	if m != nil {
		return m.FollowId
	}
	return ""
}

type CreateFollowResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	FollowingUser        *User    `protobuf:"bytes,2,opt,name=following_user,json=followingUser,proto3" json:"following_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFollowResponse) Reset()         { *m = CreateFollowResponse{} }
func (m *CreateFollowResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFollowResponse) ProtoMessage()    {}
func (*CreateFollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{11}
}

func (m *CreateFollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFollowResponse.Unmarshal(m, b)
}
func (m *CreateFollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFollowResponse.Marshal(b, m, deterministic)
}
func (m *CreateFollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFollowResponse.Merge(m, src)
}
func (m *CreateFollowResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFollowResponse.Size(m)
}
func (m *CreateFollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFollowResponse proto.InternalMessageInfo

func (m *CreateFollowResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateFollowResponse) GetFollowingUser() *User {
	if m != nil {
		return m.FollowingUser
	}
	return nil
}

type Post struct {
	PostId               string     `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte     `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	LikeCount            uint32     `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	TopComments          []*Comment `protobuf:"bytes,4,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	CommentCount         uint32     `protobuf:"varint,5,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UserId               string     `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string     `protobuf:"bytes,7,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAtSeconds     uint32     `protobuf:"fixed32,8,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{12}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Post) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *Post) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Post) GetTopComments() []*Comment {
	if m != nil {
		return m.TopComments
	}
	return nil
}

func (m *Post) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Post) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Comment struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LikeCount            uint32   `protobuf:"varint,4,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,5,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{13}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Comment) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Comment) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Like struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,2,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Like) Reset()         { *m = Like{} }
func (m *Like) String() string { return proto.CompactTextString(m) }
func (*Like) ProtoMessage()    {}
func (*Like) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{14}
}

func (m *Like) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Like.Unmarshal(m, b)
}
func (m *Like) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Like.Marshal(b, m, deterministic)
}
func (m *Like) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Like.Merge(m, src)
}
func (m *Like) XXX_Size() int {
	return xxx_messageInfo_Like.Size(m)
}
func (m *Like) XXX_DiscardUnknown() {
	xxx_messageInfo_Like.DiscardUnknown(m)
}

var xxx_messageInfo_Like proto.InternalMessageInfo

func (m *Like) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Like) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type CreatePostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{15}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type CreateLikeRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLikeRequest) Reset()         { *m = CreateLikeRequest{} }
func (m *CreateLikeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLikeRequest) ProtoMessage()    {}
func (*CreateLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{16}
}

func (m *CreateLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLikeRequest.Unmarshal(m, b)
}
func (m *CreateLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLikeRequest.Marshal(b, m, deterministic)
}
func (m *CreateLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLikeRequest.Merge(m, src)
}
func (m *CreateLikeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLikeRequest.Size(m)
}
func (m *CreateLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLikeRequest proto.InternalMessageInfo

func (m *CreateLikeRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreateLikeRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreateLikeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateLikeRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type CreateCommentRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{17}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreateCommentRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreateCommentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type GetPostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{18}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type GetFeedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedRequest) Reset()         { *m = GetFeedRequest{} }
func (m *GetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRequest) ProtoMessage()    {}
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{19}
}

func (m *GetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedRequest.Unmarshal(m, b)
}
func (m *GetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRequest.Merge(m, src)
}
func (m *GetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedRequest.Size(m)
}
func (m *GetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRequest proto.InternalMessageInfo

func (m *GetFeedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFeedRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFeedResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedResponse) Reset()         { *m = GetFeedResponse{} }
func (m *GetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedResponse) ProtoMessage()    {}
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{20}
}

func (m *GetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedResponse.Unmarshal(m, b)
}
func (m *GetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedResponse.Merge(m, src)
}
func (m *GetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedResponse.Size(m)
}
func (m *GetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedResponse proto.InternalMessageInfo

func (m *GetFeedResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type CommentsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsRequest) Reset()         { *m = CommentsRequest{} }
func (m *CommentsRequest) String() string { return proto.CompactTextString(m) }
func (*CommentsRequest) ProtoMessage()    {}
func (*CommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{21}
}

func (m *CommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsRequest.Unmarshal(m, b)
}
func (m *CommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsRequest.Marshal(b, m, deterministic)
}
func (m *CommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsRequest.Merge(m, src)
}
func (m *CommentsRequest) XXX_Size() int {
	return xxx_messageInfo_CommentsRequest.Size(m)
}
func (m *CommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsRequest proto.InternalMessageInfo

func (m *CommentsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CommentsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CommentsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsResponse) Reset()         { *m = CommentsResponse{} }
func (m *CommentsResponse) String() string { return proto.CompactTextString(m) }
func (*CommentsResponse) ProtoMessage()    {}
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{22}
}

func (m *CommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsResponse.Unmarshal(m, b)
}
func (m *CommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsResponse.Marshal(b, m, deterministic)
}
func (m *CommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsResponse.Merge(m, src)
}
func (m *CommentsResponse) XXX_Size() int {
	return xxx_messageInfo_CommentsResponse.Size(m)
}
func (m *CommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsResponse proto.InternalMessageInfo

func (m *CommentsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type PostLikesRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostLikesRequest) Reset()         { *m = PostLikesRequest{} }
func (m *PostLikesRequest) String() string { return proto.CompactTextString(m) }
func (*PostLikesRequest) ProtoMessage()    {}
func (*PostLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{23}
}

func (m *PostLikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostLikesRequest.Unmarshal(m, b)
}
func (m *PostLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostLikesRequest.Marshal(b, m, deterministic)
}
func (m *PostLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostLikesRequest.Merge(m, src)
}
func (m *PostLikesRequest) XXX_Size() int {
	return xxx_messageInfo_PostLikesRequest.Size(m)
}
func (m *PostLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostLikesRequest proto.InternalMessageInfo

func (m *PostLikesRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostLikesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CommentLikesRequest struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentLikesRequest) Reset()         { *m = CommentLikesRequest{} }
func (m *CommentLikesRequest) String() string { return proto.CompactTextString(m) }
func (*CommentLikesRequest) ProtoMessage()    {}
func (*CommentLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{24}
}

func (m *CommentLikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentLikesRequest.Unmarshal(m, b)
}
func (m *CommentLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentLikesRequest.Marshal(b, m, deterministic)
}
func (m *CommentLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentLikesRequest.Merge(m, src)
}
func (m *CommentLikesRequest) XXX_Size() int {
	return xxx_messageInfo_CommentLikesRequest.Size(m)
}
func (m *CommentLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentLikesRequest proto.InternalMessageInfo

func (m *CommentLikesRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CommentLikesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type LikesResponse struct {
	Likes                []*Like  `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikesResponse) Reset()         { *m = LikesResponse{} }
func (m *LikesResponse) String() string { return proto.CompactTextString(m) }
func (*LikesResponse) ProtoMessage()    {}
func (*LikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{25}
}

func (m *LikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikesResponse.Unmarshal(m, b)
}
func (m *LikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikesResponse.Marshal(b, m, deterministic)
}
func (m *LikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesResponse.Merge(m, src)
}
func (m *LikesResponse) XXX_Size() int {
	return xxx_messageInfo_LikesResponse.Size(m)
}
func (m *LikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikesResponse proto.InternalMessageInfo

func (m *LikesResponse) GetLikes() []*Like {
	if m != nil {
		return m.Likes
	}
	return nil
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "pb.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "pb.SignInResponse")
	proto.RegisterType((*SignUpRequest)(nil), "pb.SignUpRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetFollowersRequest)(nil), "pb.GetFollowersRequest")
	proto.RegisterType((*GetFollowersResponse)(nil), "pb.GetFollowersResponse")
	proto.RegisterType((*GetFollowingRequest)(nil), "pb.GetFollowingRequest")
	proto.RegisterType((*GetFollowingResponse)(nil), "pb.GetFollowingResponse")
	proto.RegisterType((*CreateFollowRequest)(nil), "pb.CreateFollowRequest")
	proto.RegisterType((*CreateFollowResponse)(nil), "pb.CreateFollowResponse")
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Comment)(nil), "pb.Comment")
	proto.RegisterType((*Like)(nil), "pb.Like")
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
	proto.RegisterType((*CreateLikeRequest)(nil), "pb.CreateLikeRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "pb.CreateCommentRequest")
	proto.RegisterType((*GetPostRequest)(nil), "pb.GetPostRequest")
	proto.RegisterType((*GetFeedRequest)(nil), "pb.GetFeedRequest")
	proto.RegisterType((*GetFeedResponse)(nil), "pb.GetFeedResponse")
	proto.RegisterType((*CommentsRequest)(nil), "pb.CommentsRequest")
	proto.RegisterType((*CommentsResponse)(nil), "pb.CommentsResponse")
	proto.RegisterType((*PostLikesRequest)(nil), "pb.PostLikesRequest")
	proto.RegisterType((*CommentLikesRequest)(nil), "pb.CommentLikesRequest")
	proto.RegisterType((*LikesResponse)(nil), "pb.LikesResponse")
}

func init() { proto.RegisterFile("portal.proto", fileDescriptor_ead6f188e0e8e0b1) }

var fileDescriptor_ead6f188e0e8e0b1 = []byte{
	// 1017 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xde, 0x38, 0x4e, 0x9c, 0x9c, 0xfc, 0xec, 0xee, 0x24, 0xa8, 0x26, 0xfc, 0x28, 0x32, 0x02,
	0x52, 0x09, 0xed, 0xaa, 0x29, 0x20, 0x81, 0x44, 0xab, 0x65, 0x51, 0x4b, 0x04, 0x48, 0x55, 0x56,
	0x7b, 0xc3, 0x4d, 0xe4, 0x8d, 0xa7, 0x61, 0xd4, 0xc4, 0x63, 0x3c, 0x0e, 0x15, 0x12, 0xcf, 0xc0,
	0xb3, 0x70, 0xc1, 0x6b, 0xf0, 0x3c, 0xdc, 0xa2, 0xf9, 0xb3, 0x67, 0xbc, 0x76, 0x37, 0xb4, 0x52,
	0xef, 0x72, 0xce, 0x9c, 0xf3, 0xcd, 0x37, 0xe7, 0xd7, 0x81, 0x7e, 0x42, 0xd3, 0x2c, 0xdc, 0x9e,
	0x25, 0x29, 0xcd, 0x28, 0x72, 0x92, 0x9b, 0xe0, 0x02, 0x06, 0x57, 0x64, 0x13, 0x2f, 0xe2, 0x25,
	0xfe, 0x75, 0x8f, 0x59, 0x86, 0xc6, 0xd0, 0xc2, 0xbb, 0x90, 0x6c, 0xfd, 0xc6, 0xb4, 0x31, 0xeb,
	0x2e, 0xa5, 0x80, 0x26, 0xd0, 0x49, 0x42, 0xc6, 0x5e, 0xd2, 0x34, 0xf2, 0x1d, 0x71, 0x90, 0xcb,
	0xc1, 0x77, 0x30, 0xd4, 0x10, 0x2c, 0xa1, 0x31, 0xc3, 0xe8, 0x1e, 0x78, 0x7b, 0x86, 0xd3, 0x15,
	0x89, 0x14, 0x4a, 0x9b, 0x8b, 0x8b, 0x08, 0xbd, 0x0b, 0x1d, 0xc2, 0x56, 0x61, 0xb4, 0x23, 0xb1,
	0xdf, 0x9c, 0x36, 0x66, 0x9d, 0xa5, 0x47, 0xd8, 0x05, 0x17, 0x83, 0x9f, 0x25, 0x91, 0xeb, 0xe4,
	0xd5, 0x44, 0x0c, 0x68, 0xc7, 0x82, 0x36, 0x19, 0x36, 0x4b, 0x0c, 0xff, 0x71, 0xc0, 0xbd, 0x66,
	0x38, 0xad, 0x27, 0xf6, 0x31, 0x0c, 0x9f, 0xd3, 0xed, 0x96, 0xbe, 0xc4, 0xe9, 0x6a, 0x4d, 0xf7,
	0x71, 0x26, 0xd0, 0x07, 0xcb, 0x81, 0xd6, 0x5e, 0x72, 0x25, 0xfa, 0x14, 0x8e, 0xa5, 0x82, 0xc4,
	0x1b, 0x65, 0xd7, 0x14, 0x76, 0xc3, 0x5c, 0x9d, 0x1b, 0x26, 0x29, 0x7d, 0x4e, 0xb6, 0x78, 0x95,
	0x90, 0x75, 0xb6, 0x4f, 0xb1, 0xef, 0x4e, 0x1b, 0xb3, 0xfe, 0x72, 0xa8, 0xd4, 0xcf, 0xa4, 0x16,
	0x21, 0x70, 0xe3, 0x70, 0x87, 0xfd, 0x96, 0xa0, 0x23, 0x7e, 0xa3, 0x29, 0xf4, 0x22, 0xcc, 0xd6,
	0x29, 0x49, 0x32, 0x42, 0x63, 0xbf, 0x2d, 0x8e, 0x4c, 0x15, 0x7f, 0x2c, 0x27, 0x2e, 0x3c, 0x3d,
	0xf9, 0x58, 0x2d, 0xa3, 0x0f, 0x00, 0x12, 0xca, 0x32, 0x45, 0xaf, 0x23, 0xe8, 0x75, 0xb9, 0x46,
	0x32, 0xfb, 0x0c, 0xd0, 0x3a, 0xc5, 0x61, 0x86, 0xa3, 0x55, 0x98, 0xad, 0x18, 0x5e, 0xd3, 0x38,
	0x62, 0x7e, 0x77, 0xda, 0x98, 0x79, 0xcb, 0x13, 0x75, 0x72, 0x91, 0x5d, 0x49, 0x7d, 0x91, 0x04,
	0x30, 0x92, 0x10, 0xa4, 0x70, 0x7a, 0x29, 0x2c, 0x79, 0x50, 0x75, 0xbe, 0x6a, 0x63, 0x6b, 0x92,
	0x75, 0x4a, 0x64, 0x73, 0xfc, 0xa6, 0x99, 0x64, 0x1d, 0x14, 0xb7, 0x08, 0x4a, 0x70, 0x1f, 0x86,
	0x4f, 0x71, 0x76, 0xc8, 0x85, 0xc1, 0xb7, 0x30, 0x7a, 0x8a, 0xb3, 0x27, 0x2a, 0x73, 0xec, 0x4e,
	0x82, 0x08, 0xdc, 0x24, 0xdc, 0x60, 0x95, 0x72, 0xf1, 0x3b, 0x78, 0x04, 0x63, 0x1b, 0x43, 0x95,
	0xf6, 0x27, 0xd0, 0xd5, 0x25, 0xc1, 0xfc, 0xc6, 0xb4, 0x39, 0xeb, 0xcd, 0x3b, 0x67, 0xc9, 0xcd,
	0x99, 0x20, 0x56, 0x1c, 0x59, 0x1c, 0x48, 0xbc, 0x79, 0x63, 0x0e, 0x02, 0xa3, 0xcc, 0x81, 0xc4,
	0x9b, 0x3a, 0x0e, 0x24, 0xde, 0x04, 0x3f, 0xc0, 0x48, 0xa6, 0x49, 0x42, 0xdc, 0xc9, 0xe1, 0x3d,
	0x8d, 0x5b, 0x74, 0x57, 0x47, 0x2a, 0x16, 0x51, 0x80, 0x61, 0x6c, 0x83, 0x29, 0x32, 0xef, 0x83,
	0xcb, 0xdd, 0x05, 0x94, 0xc9, 0x43, 0x68, 0xd1, 0x39, 0x14, 0x9d, 0xb1, 0x12, 0x76, 0x4e, 0xc9,
	0x6e, 0x90, 0x9f, 0x73, 0x31, 0xf8, 0xd3, 0x01, 0xf7, 0x19, 0x95, 0x2c, 0x45, 0x19, 0x17, 0x2c,
	0xb9, 0xb8, 0x88, 0x90, 0x0f, 0x9e, 0x6e, 0x29, 0x47, 0xb4, 0x94, 0x16, 0x79, 0xe5, 0x6f, 0xc9,
	0x0b, 0x6c, 0x35, 0x66, 0x97, 0x6b, 0x64, 0xe5, 0x9f, 0x41, 0x3f, 0xa3, 0xc9, 0x6a, 0x4d, 0x77,
	0x3b, 0x1c, 0x67, 0xcc, 0x77, 0x45, 0xe4, 0x7a, 0x9c, 0xc9, 0xa5, 0xd4, 0x2d, 0x7b, 0x19, 0x4d,
	0xd4, 0x6f, 0x86, 0x3e, 0x82, 0x81, 0xb2, 0x55, 0x88, 0x2d, 0x81, 0xd8, 0x57, 0x4a, 0x09, 0x6a,
	0x04, 0xb3, 0x6d, 0x05, 0xd3, 0x07, 0x6f, 0x1d, 0xca, 0x06, 0x96, 0x1d, 0xaa, 0xc5, 0x9a, 0x0e,
	0xec, 0x54, 0x77, 0x60, 0xf0, 0x57, 0x03, 0x3c, 0x45, 0x89, 0x3f, 0x50, 0x33, 0xca, 0xc3, 0xd2,
	0x55, 0x9a, 0x45, 0x54, 0x3f, 0x1b, 0x4b, 0x03, 0xa5, 0x79, 0x7b, 0xa0, 0xd8, 0xa1, 0x73, 0xcb,
	0xa1, 0xab, 0xa6, 0xdc, 0xaa, 0xa1, 0xfc, 0x13, 0xb8, 0x3f, 0x92, 0x17, 0xaf, 0x58, 0x03, 0xd5,
	0x70, 0x4e, 0x0d, 0xdc, 0xef, 0x7a, 0xda, 0xf0, 0xba, 0x30, 0x8a, 0xf8, 0xff, 0x96, 0x87, 0x41,
	0xa7, 0x59, 0x97, 0x2a, 0xd7, 0x4a, 0x55, 0x71, 0x35, 0x7f, 0xcf, 0xdb, 0xbd, 0xfa, 0x0f, 0xdd,
	0x6f, 0xba, 0x36, 0xdf, 0xea, 0xed, 0x72, 0xda, 0x1e, 0x12, 0xf0, 0xe0, 0x1b, 0x61, 0xfa, 0x04,
	0xe3, 0xe8, 0xb5, 0x86, 0xdc, 0x03, 0x38, 0xce, 0xdd, 0xd5, 0x48, 0xf9, 0x10, 0x5a, 0x1c, 0xdb,
	0x9a, 0xaf, 0x82, 0x8a, 0x54, 0x07, 0x8f, 0xe0, 0x58, 0x37, 0xe9, 0x6b, 0x5d, 0x39, 0x87, 0x93,
	0xc2, 0xff, 0xc0, 0x3b, 0x1f, 0xc3, 0x09, 0x17, 0x79, 0x1d, 0xb0, 0x3b, 0x53, 0x51, 0x75, 0xe9,
	0xf7, 0x30, 0x52, 0x97, 0x5a, 0x18, 0x77, 0xb4, 0x74, 0x15, 0xd2, 0x39, 0x0c, 0x14, 0x44, 0xc1,
	0x9d, 0xb7, 0xaa, 0xc5, 0x5d, 0x14, 0xac, 0x54, 0xcf, 0x29, 0x78, 0x17, 0xfb, 0xec, 0x97, 0xab,
	0xdf, 0xd6, 0xe8, 0x01, 0xb4, 0xe5, 0xb7, 0x1a, 0x3a, 0xe5, 0x56, 0xd6, 0xa7, 0xdf, 0x04, 0x99,
	0x2a, 0x89, 0x1d, 0x1c, 0x69, 0x97, 0xeb, 0xa4, 0x70, 0xc9, 0x3f, 0xd2, 0xaa, 0x5d, 0xe6, 0x7f,
	0x3b, 0xe0, 0xf1, 0x69, 0xce, 0x6f, 0x3c, 0x07, 0x28, 0xbe, 0x15, 0xd0, 0x3b, 0x62, 0xda, 0x96,
	0xbf, 0x1d, 0x26, 0xf9, 0x3a, 0x08, 0x8e, 0xd0, 0x7d, 0xf0, 0xd4, 0xa2, 0x47, 0x02, 0xdd, 0xde,
	0xfa, 0x96, 0xe9, 0x25, 0xf4, 0xcd, 0x25, 0x8d, 0xee, 0x29, 0xfb, 0xf2, 0xea, 0x9f, 0xf8, 0xb7,
	0x0f, 0xf2, 0xf7, 0x99, 0x20, 0x24, 0xde, 0x94, 0x40, 0x8a, 0xdd, 0x5d, 0x02, 0x31, 0x16, 0xb2,
	0x04, 0x31, 0xb7, 0xa3, 0x04, 0xa9, 0x58, 0xbe, 0x12, 0xa4, 0x6a, 0x91, 0x06, 0x47, 0xf3, 0x7f,
	0x9b, 0xe0, 0xf1, 0x22, 0xb3, 0xc2, 0x26, 0x96, 0xa1, 0x11, 0x36, 0xa3, 0x27, 0x27, 0x79, 0x95,
	0x06, 0x47, 0xe8, 0x21, 0x0c, 0x0b, 0x03, 0x31, 0x7e, 0x0d, 0x27, 0x63, 0x7c, 0x59, 0x4e, 0x5f,
	0xea, 0xf9, 0x66, 0x94, 0xe6, 0x21, 0x7e, 0x5f, 0xc0, 0xc0, 0xf2, 0x43, 0xc6, 0xb3, 0xec, 0x79,
	0x65, 0xb9, 0xc9, 0xd4, 0x8a, 0x17, 0xe9, 0xd4, 0xd6, 0x3d, 0xe7, 0x73, 0x61, 0xca, 0xc7, 0x42,
	0x6e, 0x6a, 0x8c, 0x98, 0xc9, 0xc8, 0xd2, 0xe5, 0x69, 0xf8, 0x4a, 0xe4, 0x32, 0x6f, 0x54, 0x34,
	0xd6, 0x88, 0x66, 0xcf, 0x4d, 0x4e, 0x75, 0x83, 0x98, 0x65, 0xf0, 0x58, 0xcc, 0x21, 0xb3, 0x45,
	0x55, 0x12, 0x6f, 0x37, 0x6d, 0x35, 0xc0, 0xd7, 0xd0, 0x2b, 0x00, 0x18, 0x1a, 0x19, 0xce, 0xb9,
	0xe3, 0xd8, 0x56, 0x6a, 0xdf, 0x9b, 0xb6, 0xf8, 0x43, 0xf6, 0xf0, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xb3, 0xe1, 0xe8, 0xa0, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthSvcClient is the client API for AuthSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthSvcClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type authSvcClient struct {
	cc *grpc.ClientConn
}

func NewAuthSvcClient(cc *grpc.ClientConn) AuthSvcClient {
	return &authSvcClient{cc}
}

func (c *authSvcClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthSvc/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthSvc/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSvcServer is the server API for AuthSvc service.
type AuthSvcServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignUp(context.Context, *SignUpRequest) (*SignInResponse, error)
}

// UnimplementedAuthSvcServer can be embedded to have forward compatible implementations.
type UnimplementedAuthSvcServer struct {
}

func (*UnimplementedAuthSvcServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthSvcServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterAuthSvcServer(s *grpc.Server, srv AuthSvcServer) {
	s.RegisterService(&_AuthSvc_serviceDesc, srv)
}

func _AuthSvc_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthSvc/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthSvc/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthSvc",
	HandlerType: (*AuthSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AuthSvc_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AuthSvc_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
	GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
	CreateFollow(ctx context.Context, in *CreateFollowRequest, opts ...grpc.CallOption) (*CreateFollowResponse, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	out := new(GetFollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) CreateFollow(ctx context.Context, in *CreateFollowRequest, opts ...grpc.CallOption) (*CreateFollowResponse, error) {
	out := new(CreateFollowResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/CreateFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error)
	CreateFollow(context.Context, *CreateFollowRequest) (*CreateFollowResponse, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserSvcServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserSvcServer) GetFollowers(ctx context.Context, req *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (*UnimplementedUserSvcServer) GetFollowing(ctx context.Context, req *GetFollowingRequest) (*GetFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}
func (*UnimplementedUserSvcServer) CreateFollow(ctx context.Context, req *CreateFollowRequest) (*CreateFollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFollow not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetFollowing(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_CreateFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/CreateFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateFollow(ctx, req.(*CreateFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserSvc_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserSvc_GetUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _UserSvc_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _UserSvc_GetFollowing_Handler,
		},
		{
			MethodName: "CreateFollow",
			Handler:    _UserSvc_CreateFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// PostSvcClient is the client API for PostSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostSvcClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error)
	CreatePostLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error)
	CreateCommentLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Post, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	GetPostLikes(ctx context.Context, in *PostLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetCommentLikes(ctx context.Context, in *CommentLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
}

type postSvcClient struct {
	cc *grpc.ClientConn
}

func NewPostSvcClient(cc *grpc.ClientConn) PostSvcClient {
	return &postSvcClient{cc}
}

func (c *postSvcClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreatePostLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreatePostLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreateCommentLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreateCommentLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetPostLikes(ctx context.Context, in *PostLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetPostLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetCommentLikes(ctx context.Context, in *CommentLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetCommentLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSvcServer is the server API for PostSvc service.
type PostSvcServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*Post, error)
	CreatePostLike(context.Context, *CreateLikeRequest) (*Post, error)
	CreateCommentLike(context.Context, *CreateLikeRequest) (*Post, error)
	CreateComment(context.Context, *CreateCommentRequest) (*Post, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	GetPostLikes(context.Context, *PostLikesRequest) (*LikesResponse, error)
	GetCommentLikes(context.Context, *CommentLikesRequest) (*LikesResponse, error)
	GetComments(context.Context, *CommentsRequest) (*CommentsResponse, error)
}

// UnimplementedPostSvcServer can be embedded to have forward compatible implementations.
type UnimplementedPostSvcServer struct {
}

func (*UnimplementedPostSvcServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostSvcServer) CreatePostLike(ctx context.Context, req *CreateLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePostLike not implemented")
}
func (*UnimplementedPostSvcServer) CreateCommentLike(ctx context.Context, req *CreateLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommentLike not implemented")
}
func (*UnimplementedPostSvcServer) CreateComment(ctx context.Context, req *CreateCommentRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedPostSvcServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostSvcServer) GetFeed(ctx context.Context, req *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (*UnimplementedPostSvcServer) GetPostLikes(ctx context.Context, req *PostLikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikes not implemented")
}
func (*UnimplementedPostSvcServer) GetCommentLikes(ctx context.Context, req *CommentLikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentLikes not implemented")
}
func (*UnimplementedPostSvcServer) GetComments(ctx context.Context, req *CommentsRequest) (*CommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}

func RegisterPostSvcServer(s *grpc.Server, srv PostSvcServer) {
	s.RegisterService(&_PostSvc_serviceDesc, srv)
}

func _PostSvc_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreatePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreatePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreatePostLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreatePostLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreateCommentLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreateCommentLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreateCommentLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreateCommentLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetPostLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetPostLikes(ctx, req.(*PostLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetCommentLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetCommentLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetCommentLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetCommentLikes(ctx, req.(*CommentLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetComments(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostSvc",
	HandlerType: (*PostSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostSvc_CreatePost_Handler,
		},
		{
			MethodName: "CreatePostLike",
			Handler:    _PostSvc_CreatePostLike_Handler,
		},
		{
			MethodName: "CreateCommentLike",
			Handler:    _PostSvc_CreateCommentLike_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostSvc_CreateComment_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostSvc_GetPost_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _PostSvc_GetFeed_Handler,
		},
		{
			MethodName: "GetPostLikes",
			Handler:    _PostSvc_GetPostLikes_Handler,
		},
		{
			MethodName: "GetCommentLikes",
			Handler:    _PostSvc_GetCommentLikes_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _PostSvc_GetComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}
