// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignInResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowerCount        uint32   `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FileId               string   `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	PostCount            uint32   `protobuf:"varint,8,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *User) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *User) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetFollowersRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersRequest) Reset()         { *m = GetFollowersRequest{} }
func (m *GetFollowersRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowersRequest) ProtoMessage()    {}
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{6}
}

func (m *GetFollowersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersRequest.Unmarshal(m, b)
}
func (m *GetFollowersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersRequest.Merge(m, src)
}
func (m *GetFollowersRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowersRequest.Size(m)
}
func (m *GetFollowersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersRequest proto.InternalMessageInfo

func (m *GetFollowersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFollowersRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFollowersResponse struct {
	Followers            []*User  `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersResponse) Reset()         { *m = GetFollowersResponse{} }
func (m *GetFollowersResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowersResponse) ProtoMessage()    {}
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{7}
}

func (m *GetFollowersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersResponse.Unmarshal(m, b)
}
func (m *GetFollowersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersResponse.Merge(m, src)
}
func (m *GetFollowersResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowersResponse.Size(m)
}
func (m *GetFollowersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersResponse proto.InternalMessageInfo

func (m *GetFollowersResponse) GetFollowers() []*User {
	if m != nil {
		return m.Followers
	}
	return nil
}

type GetFollowingRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowingRequest) Reset()         { *m = GetFollowingRequest{} }
func (m *GetFollowingRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowingRequest) ProtoMessage()    {}
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{8}
}

func (m *GetFollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingRequest.Unmarshal(m, b)
}
func (m *GetFollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingRequest.Marshal(b, m, deterministic)
}
func (m *GetFollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingRequest.Merge(m, src)
}
func (m *GetFollowingRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowingRequest.Size(m)
}
func (m *GetFollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingRequest proto.InternalMessageInfo

func (m *GetFollowingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFollowingRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFollowingResponse struct {
	Following            []*User  `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowingResponse) Reset()         { *m = GetFollowingResponse{} }
func (m *GetFollowingResponse) String() string { return proto.CompactTextString(m) }
func (*GetFollowingResponse) ProtoMessage()    {}
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{9}
}

func (m *GetFollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowingResponse.Unmarshal(m, b)
}
func (m *GetFollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowingResponse.Marshal(b, m, deterministic)
}
func (m *GetFollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowingResponse.Merge(m, src)
}
func (m *GetFollowingResponse) XXX_Size() int {
	return xxx_messageInfo_GetFollowingResponse.Size(m)
}
func (m *GetFollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowingResponse proto.InternalMessageInfo

func (m *GetFollowingResponse) GetFollowing() []*User {
	if m != nil {
		return m.Following
	}
	return nil
}

type FollowRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowId             string   `protobuf:"bytes,2,opt,name=follow_id,json=followId,proto3" json:"follow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{10}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FollowRequest) GetFollowId() string {
	if m != nil {
		return m.FollowId
	}
	return ""
}

type FollowResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	FollowingUser        *User    `protobuf:"bytes,2,opt,name=following_user,json=followingUser,proto3" json:"following_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowResponse) Reset()         { *m = FollowResponse{} }
func (m *FollowResponse) String() string { return proto.CompactTextString(m) }
func (*FollowResponse) ProtoMessage()    {}
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{11}
}

func (m *FollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowResponse.Unmarshal(m, b)
}
func (m *FollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowResponse.Marshal(b, m, deterministic)
}
func (m *FollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowResponse.Merge(m, src)
}
func (m *FollowResponse) XXX_Size() int {
	return xxx_messageInfo_FollowResponse.Size(m)
}
func (m *FollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowResponse proto.InternalMessageInfo

func (m *FollowResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *FollowResponse) GetFollowingUser() *User {
	if m != nil {
		return m.FollowingUser
	}
	return nil
}

type Post struct {
	PostId               string     `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	FileId               string     `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	LikeCount            uint32     `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	TopComments          []*Comment `protobuf:"bytes,4,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	CommentCount         uint32     `protobuf:"varint,5,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UserId               string     `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string     `protobuf:"bytes,7,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAtSeconds     uint32     `protobuf:"fixed32,8,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{12}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Post) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *Post) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Post) GetTopComments() []*Comment {
	if m != nil {
		return m.TopComments
	}
	return nil
}

func (m *Post) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Post) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Comment struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               string   `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LikeCount            uint32   `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,6,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{13}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Comment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Comment) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Comment) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Like struct {
	LikeId               string   `protobuf:"bytes,1,opt,name=like_id,json=likeId,proto3" json:"like_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               string   `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,4,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Like) Reset()         { *m = Like{} }
func (m *Like) String() string { return proto.CompactTextString(m) }
func (*Like) ProtoMessage()    {}
func (*Like) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{14}
}

func (m *Like) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Like.Unmarshal(m, b)
}
func (m *Like) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Like.Marshal(b, m, deterministic)
}
func (m *Like) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Like.Merge(m, src)
}
func (m *Like) XXX_Size() int {
	return xxx_messageInfo_Like.Size(m)
}
func (m *Like) XXX_DiscardUnknown() {
	xxx_messageInfo_Like.DiscardUnknown(m)
}

var xxx_messageInfo_Like proto.InternalMessageInfo

func (m *Like) GetLikeId() string {
	if m != nil {
		return m.LikeId
	}
	return ""
}

func (m *Like) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Like) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Like) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type CreatePostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	FileId               string   `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{15}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *CreatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type CreatePostLikeRequest struct {
	LikeId               string   `protobuf:"bytes,1,opt,name=like_id,json=likeId,proto3" json:"like_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               string   `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostLikeRequest) Reset()         { *m = CreatePostLikeRequest{} }
func (m *CreatePostLikeRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostLikeRequest) ProtoMessage()    {}
func (*CreatePostLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{16}
}

func (m *CreatePostLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostLikeRequest.Unmarshal(m, b)
}
func (m *CreatePostLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostLikeRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostLikeRequest.Merge(m, src)
}
func (m *CreatePostLikeRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostLikeRequest.Size(m)
}
func (m *CreatePostLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostLikeRequest proto.InternalMessageInfo

func (m *CreatePostLikeRequest) GetLikeId() string {
	if m != nil {
		return m.LikeId
	}
	return ""
}

func (m *CreatePostLikeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostLikeRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type CreateCommentLikeRequest struct {
	LikeId               string   `protobuf:"bytes,1,opt,name=like_id,json=likeId,proto3" json:"like_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId            string   `protobuf:"bytes,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentLikeRequest) Reset()         { *m = CreateCommentLikeRequest{} }
func (m *CreateCommentLikeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentLikeRequest) ProtoMessage()    {}
func (*CreateCommentLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{17}
}

func (m *CreateCommentLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentLikeRequest.Unmarshal(m, b)
}
func (m *CreateCommentLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentLikeRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentLikeRequest.Merge(m, src)
}
func (m *CreateCommentLikeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentLikeRequest.Size(m)
}
func (m *CreateCommentLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentLikeRequest proto.InternalMessageInfo

func (m *CreateCommentLikeRequest) GetLikeId() string {
	if m != nil {
		return m.LikeId
	}
	return ""
}

func (m *CreateCommentLikeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentLikeRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type CreateCommentRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId            string   `protobuf:"bytes,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{18}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreateCommentRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CreateCommentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type CreateCommentResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Comment              *Comment `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{19}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

func (m *CreateCommentResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *CreateCommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type GetPostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{20}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type GetPostsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsRequest) Reset()         { *m = GetPostsRequest{} }
func (m *GetPostsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostsRequest) ProtoMessage()    {}
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{21}
}

func (m *GetPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsRequest.Unmarshal(m, b)
}
func (m *GetPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsRequest.Merge(m, src)
}
func (m *GetPostsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostsRequest.Size(m)
}
func (m *GetPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsRequest proto.InternalMessageInfo

func (m *GetPostsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetPostsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextPage             uint32   `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsResponse) Reset()         { *m = GetPostsResponse{} }
func (m *GetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse) ProtoMessage()    {}
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{22}
}

func (m *GetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse.Unmarshal(m, b)
}
func (m *GetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse.Merge(m, src)
}
func (m *GetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse.Size(m)
}
func (m *GetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse proto.InternalMessageInfo

func (m *GetPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetPostsResponse) GetNextPage() uint32 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

type GetCommentRequest struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentRequest) Reset()         { *m = GetCommentRequest{} }
func (m *GetCommentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentRequest) ProtoMessage()    {}
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{23}
}

func (m *GetCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentRequest.Unmarshal(m, b)
}
func (m *GetCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentRequest.Merge(m, src)
}
func (m *GetCommentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentRequest.Size(m)
}
func (m *GetCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentRequest proto.InternalMessageInfo

func (m *GetCommentRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type GetPostCommentsRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostCommentsRequest) Reset()         { *m = GetPostCommentsRequest{} }
func (m *GetPostCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostCommentsRequest) ProtoMessage()    {}
func (*GetPostCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{24}
}

func (m *GetPostCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostCommentsRequest.Unmarshal(m, b)
}
func (m *GetPostCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostCommentsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostCommentsRequest.Merge(m, src)
}
func (m *GetPostCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostCommentsRequest.Size(m)
}
func (m *GetPostCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostCommentsRequest proto.InternalMessageInfo

func (m *GetPostCommentsRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *GetPostCommentsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CommentsResponse struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextPage             uint32     `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommentsResponse) Reset()         { *m = CommentsResponse{} }
func (m *CommentsResponse) String() string { return proto.CompactTextString(m) }
func (*CommentsResponse) ProtoMessage()    {}
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{25}
}

func (m *CommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsResponse.Unmarshal(m, b)
}
func (m *CommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsResponse.Marshal(b, m, deterministic)
}
func (m *CommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsResponse.Merge(m, src)
}
func (m *CommentsResponse) XXX_Size() int {
	return xxx_messageInfo_CommentsResponse.Size(m)
}
func (m *CommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsResponse proto.InternalMessageInfo

func (m *CommentsResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *CommentsResponse) GetNextPage() uint32 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

type GetPostLikesRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostLikesRequest) Reset()         { *m = GetPostLikesRequest{} }
func (m *GetPostLikesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostLikesRequest) ProtoMessage()    {}
func (*GetPostLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{26}
}

func (m *GetPostLikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostLikesRequest.Unmarshal(m, b)
}
func (m *GetPostLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostLikesRequest.Marshal(b, m, deterministic)
}
func (m *GetPostLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostLikesRequest.Merge(m, src)
}
func (m *GetPostLikesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostLikesRequest.Size(m)
}
func (m *GetPostLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostLikesRequest proto.InternalMessageInfo

func (m *GetPostLikesRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *GetPostLikesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetCommentLikesRequest struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentLikesRequest) Reset()         { *m = GetCommentLikesRequest{} }
func (m *GetCommentLikesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentLikesRequest) ProtoMessage()    {}
func (*GetCommentLikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{27}
}

func (m *GetCommentLikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentLikesRequest.Unmarshal(m, b)
}
func (m *GetCommentLikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentLikesRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentLikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentLikesRequest.Merge(m, src)
}
func (m *GetCommentLikesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentLikesRequest.Size(m)
}
func (m *GetCommentLikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentLikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentLikesRequest proto.InternalMessageInfo

func (m *GetCommentLikesRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *GetCommentLikesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type LikesResponse struct {
	Likes                []*Like  `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	NextPage             uint32   `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikesResponse) Reset()         { *m = LikesResponse{} }
func (m *LikesResponse) String() string { return proto.CompactTextString(m) }
func (*LikesResponse) ProtoMessage()    {}
func (*LikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{28}
}

func (m *LikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikesResponse.Unmarshal(m, b)
}
func (m *LikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikesResponse.Marshal(b, m, deterministic)
}
func (m *LikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesResponse.Merge(m, src)
}
func (m *LikesResponse) XXX_Size() int {
	return xxx_messageInfo_LikesResponse.Size(m)
}
func (m *LikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikesResponse proto.InternalMessageInfo

func (m *LikesResponse) GetLikes() []*Like {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *LikesResponse) GetNextPage() uint32 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

type FilePart struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilePart) Reset()         { *m = FilePart{} }
func (m *FilePart) String() string { return proto.CompactTextString(m) }
func (*FilePart) ProtoMessage()    {}
func (*FilePart) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{29}
}

func (m *FilePart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePart.Unmarshal(m, b)
}
func (m *FilePart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePart.Marshal(b, m, deterministic)
}
func (m *FilePart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePart.Merge(m, src)
}
func (m *FilePart) XXX_Size() int {
	return xxx_messageInfo_FilePart.Size(m)
}
func (m *FilePart) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePart.DiscardUnknown(m)
}

var xxx_messageInfo_FilePart proto.InternalMessageInfo

func (m *FilePart) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type UploadStatus struct {
	FileId               string           `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Status               UploadStatusCode `protobuf:"varint,2,opt,name=status,proto3,enum=pb.UploadStatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{30}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *UploadStatus) GetStatus() UploadStatusCode {
	if m != nil {
		return m.Status
	}
	return UploadStatusCode_Unknown
}

func init() {
	proto.RegisterEnum("pb.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*SignInRequest)(nil), "pb.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "pb.SignInResponse")
	proto.RegisterType((*SignUpRequest)(nil), "pb.SignUpRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetFollowersRequest)(nil), "pb.GetFollowersRequest")
	proto.RegisterType((*GetFollowersResponse)(nil), "pb.GetFollowersResponse")
	proto.RegisterType((*GetFollowingRequest)(nil), "pb.GetFollowingRequest")
	proto.RegisterType((*GetFollowingResponse)(nil), "pb.GetFollowingResponse")
	proto.RegisterType((*FollowRequest)(nil), "pb.FollowRequest")
	proto.RegisterType((*FollowResponse)(nil), "pb.FollowResponse")
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Comment)(nil), "pb.Comment")
	proto.RegisterType((*Like)(nil), "pb.Like")
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
	proto.RegisterType((*CreatePostLikeRequest)(nil), "pb.CreatePostLikeRequest")
	proto.RegisterType((*CreateCommentLikeRequest)(nil), "pb.CreateCommentLikeRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "pb.CreateCommentRequest")
	proto.RegisterType((*CreateCommentResponse)(nil), "pb.CreateCommentResponse")
	proto.RegisterType((*GetPostRequest)(nil), "pb.GetPostRequest")
	proto.RegisterType((*GetPostsRequest)(nil), "pb.GetPostsRequest")
	proto.RegisterType((*GetPostsResponse)(nil), "pb.GetPostsResponse")
	proto.RegisterType((*GetCommentRequest)(nil), "pb.GetCommentRequest")
	proto.RegisterType((*GetPostCommentsRequest)(nil), "pb.GetPostCommentsRequest")
	proto.RegisterType((*CommentsResponse)(nil), "pb.CommentsResponse")
	proto.RegisterType((*GetPostLikesRequest)(nil), "pb.GetPostLikesRequest")
	proto.RegisterType((*GetCommentLikesRequest)(nil), "pb.GetCommentLikesRequest")
	proto.RegisterType((*LikesResponse)(nil), "pb.LikesResponse")
	proto.RegisterType((*FilePart)(nil), "pb.FilePart")
	proto.RegisterType((*UploadStatus)(nil), "pb.UploadStatus")
}

func init() { proto.RegisterFile("portal.proto", fileDescriptor_ead6f188e0e8e0b1) }

var fileDescriptor_ead6f188e0e8e0b1 = []byte{
	// 1281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xef, 0x6a, 0x1b, 0x47,
	0x10, 0x97, 0x4e, 0x27, 0x9d, 0x34, 0x96, 0x14, 0x79, 0xe3, 0xd4, 0x67, 0x35, 0x29, 0x66, 0xdb,
	0x34, 0x4e, 0x31, 0x0e, 0x55, 0xa0, 0xa1, 0xd0, 0x06, 0x1c, 0xd7, 0x36, 0xa6, 0x81, 0x18, 0x19,
	0x41, 0x29, 0x05, 0x71, 0xd6, 0x6d, 0xd4, 0xc3, 0xd2, 0xed, 0xf5, 0x6e, 0x1d, 0x1b, 0xfa, 0xa1,
	0x4f, 0xd0, 0x8f, 0x7d, 0x9c, 0x3e, 0x40, 0x1f, 0xa3, 0x6f, 0x52, 0xf6, 0xdf, 0xdd, 0xee, 0x59,
	0xf2, 0xbf, 0xf4, 0xdb, 0xed, 0xec, 0xce, 0xcc, 0x6f, 0x66, 0x67, 0x7e, 0x3b, 0x12, 0xb4, 0x13,
	0x9a, 0xb2, 0x60, 0xb6, 0x93, 0xa4, 0x94, 0x51, 0xe4, 0x24, 0xa7, 0x78, 0x17, 0x3a, 0x27, 0xd1,
	0x34, 0x3e, 0x8a, 0x87, 0xe4, 0xb7, 0x73, 0x92, 0x31, 0xb4, 0x06, 0x75, 0x32, 0x0f, 0xa2, 0x99,
	0x5f, 0xdd, 0xac, 0x6e, 0xb5, 0x86, 0x72, 0x81, 0xfa, 0xd0, 0x4c, 0x82, 0x2c, 0xbb, 0xa0, 0x69,
	0xe8, 0x3b, 0x62, 0x23, 0x5f, 0xe3, 0x1f, 0xa0, 0xab, 0x4d, 0x64, 0x09, 0x8d, 0x33, 0x82, 0xd6,
	0xc1, 0x3b, 0xcf, 0x48, 0x3a, 0x8e, 0x42, 0x65, 0xa5, 0xc1, 0x97, 0x47, 0x21, 0xda, 0x80, 0x66,
	0x94, 0x8d, 0x83, 0x70, 0x1e, 0xc5, 0x7e, 0x6d, 0xb3, 0xba, 0xd5, 0x1c, 0x7a, 0x51, 0xb6, 0xcb,
	0x97, 0xf8, 0x67, 0x09, 0x64, 0x94, 0x5c, 0x0f, 0xc4, 0x30, 0xed, 0x58, 0xa6, 0x4d, 0x84, 0xb5,
	0x12, 0xc2, 0xbf, 0x1d, 0x70, 0x47, 0x19, 0x49, 0x97, 0x03, 0x7b, 0x0a, 0xdd, 0xf7, 0x74, 0x36,
	0xa3, 0x17, 0x24, 0x1d, 0x4f, 0xe8, 0x79, 0xcc, 0x84, 0xf5, 0xce, 0xb0, 0xa3, 0xa5, 0x7b, 0x5c,
	0x88, 0x9e, 0xc1, 0x03, 0x29, 0x88, 0xe2, 0xa9, 0x3a, 0x57, 0x13, 0xe7, 0xba, 0xb9, 0x58, 0x1e,
	0x5c, 0x07, 0xef, 0x7d, 0x34, 0x23, 0xdc, 0x91, 0x2b, 0x1d, 0xf1, 0xe5, 0x51, 0x88, 0x10, 0xb8,
	0x71, 0x30, 0x27, 0x7e, 0x5d, 0x48, 0xc5, 0x37, 0xda, 0x84, 0x95, 0x90, 0x64, 0x93, 0x34, 0x4a,
	0x58, 0x44, 0x63, 0xbf, 0x21, 0xb6, 0x4c, 0x11, 0x0f, 0x8e, 0x03, 0x15, 0x9a, 0x9e, 0x0c, 0x4e,
	0xaf, 0xd1, 0x13, 0x80, 0x84, 0x66, 0x4c, 0xc1, 0x69, 0x0a, 0x38, 0x2d, 0x2e, 0x91, 0x48, 0xb6,
	0x01, 0x4d, 0x52, 0x12, 0x30, 0x12, 0x8e, 0x03, 0x36, 0xce, 0xc8, 0x84, 0xc6, 0x61, 0xe6, 0xb7,
	0x36, 0xab, 0x5b, 0xde, 0xb0, 0xa7, 0x76, 0x76, 0xd9, 0x89, 0x94, 0x17, 0x49, 0x07, 0x23, 0xe9,
	0x38, 0x85, 0xd5, 0x3d, 0x71, 0x92, 0x27, 0x51, 0xdf, 0xcf, 0xd2, 0x5c, 0x9a, 0x60, 0x9d, 0x12,
	0xd8, 0xdc, 0x7e, 0xcd, 0xbc, 0x54, 0x9d, 0x14, 0xb7, 0x48, 0x0a, 0x7e, 0x0e, 0xdd, 0x43, 0xc2,
	0x6e, 0xe3, 0x10, 0xbf, 0x81, 0x87, 0x87, 0x84, 0x1d, 0xa8, 0x9b, 0xca, 0x6e, 0x04, 0x88, 0xc0,
	0x4d, 0x82, 0x29, 0x51, 0x57, 0x2c, 0xbe, 0xf1, 0x6b, 0x58, 0xb3, 0x6d, 0xa8, 0x52, 0xfe, 0x12,
	0x5a, 0xba, 0x04, 0x32, 0xbf, 0xba, 0x59, 0xdb, 0x5a, 0x19, 0x34, 0x77, 0x92, 0xd3, 0x1d, 0x01,
	0xac, 0xd8, 0xb2, 0x30, 0x44, 0xf1, 0xf4, 0xa3, 0x31, 0x08, 0x1b, 0x65, 0x0c, 0x51, 0x3c, 0x5d,
	0x86, 0x21, 0x8a, 0xa7, 0x78, 0x1f, 0x3a, 0x52, 0xf9, 0x46, 0xef, 0x9f, 0x6a, 0x8b, 0x45, 0x1f,
	0x35, 0xa5, 0xe0, 0x28, 0xc4, 0x63, 0xe8, 0x6a, 0x33, 0x0a, 0xc0, 0x63, 0x70, 0xb9, 0xa2, 0x30,
	0x62, 0xfa, 0x16, 0x52, 0xf4, 0x02, 0x8a, 0xea, 0x1f, 0x8b, 0x73, 0x4e, 0xe9, 0x5c, 0x27, 0xdf,
	0xe7, 0x4b, 0xfc, 0xa7, 0x03, 0xee, 0x31, 0x95, 0xf8, 0x44, 0xe9, 0x16, 0xf8, 0xf8, 0xf2, 0x28,
	0x34, 0xdb, 0xc7, 0xb1, 0xda, 0xe7, 0x09, 0xc0, 0x2c, 0x3a, 0x23, 0x56, 0xef, 0xb5, 0xb8, 0x44,
	0x16, 0xfb, 0x0e, 0xb4, 0x19, 0x4d, 0xc6, 0x13, 0x3a, 0x9f, 0x93, 0x98, 0x65, 0xbe, 0x2b, 0x92,
	0xb5, 0xc2, 0x81, 0xec, 0x49, 0xd9, 0x70, 0x85, 0xd1, 0x44, 0x7d, 0x67, 0xe8, 0x73, 0xe8, 0xa8,
	0xb3, 0xca, 0x62, 0x5d, 0x58, 0x6c, 0x2b, 0x61, 0xde, 0xcb, 0x3a, 0x8b, 0x0d, 0x2b, 0x8b, 0x3e,
	0x78, 0x93, 0x40, 0xf6, 0xac, 0x6c, 0x4a, 0xbd, 0x5c, 0xd2, 0x74, 0xcd, 0xc5, 0x4d, 0x87, 0xff,
	0xa9, 0x82, 0xa7, 0x20, 0xf1, 0x00, 0x35, 0xa2, 0x3c, 0x2b, 0x2d, 0x25, 0x91, 0x89, 0x59, 0x4c,
	0x7f, 0x46, 0x2a, 0x6b, 0x56, 0x2a, 0x4b, 0xe4, 0xe2, 0x5e, 0x25, 0x17, 0x3b, 0xa7, 0xf5, 0x72,
	0x4e, 0x17, 0xc7, 0xd2, 0x58, 0x12, 0xcb, 0x1f, 0xe0, 0xbe, 0x8d, 0xce, 0xc4, 0x13, 0x20, 0x8c,
	0x16, 0x57, 0xcb, 0x97, 0xf7, 0x8a, 0x60, 0x31, 0x00, 0x77, 0x09, 0x80, 0x4b, 0xcd, 0x55, 0xbc,
	0xc2, 0x8c, 0x46, 0xb8, 0x63, 0xa1, 0x19, 0x30, 0x6b, 0xcb, 0x2e, 0xdd, 0xb5, 0x2e, 0x1d, 0x9f,
	0xc2, 0xa3, 0xc2, 0x33, 0x4f, 0x82, 0xe1, 0xfd, 0x7f, 0xca, 0x05, 0x3e, 0x03, 0x5f, 0xfa, 0x50,
	0xf5, 0xf2, 0x71, 0x6e, 0xec, 0x62, 0xab, 0x95, 0x8a, 0x0d, 0xff, 0x0e, 0x6b, 0x96, 0xb3, 0x1b,
	0xb3, 0x69, 0xdb, 0x73, 0xae, 0x29, 0xde, 0x5a, 0x99, 0x0c, 0x19, 0xb9, 0x64, 0x9a, 0xff, 0xf9,
	0x37, 0xfe, 0x45, 0x67, 0x33, 0x77, 0x5e, 0x90, 0x11, 0x77, 0x67, 0x92, 0x91, 0xb8, 0x6a, 0x21,
	0x45, 0x4f, 0xc1, 0x53, 0x0e, 0x15, 0x0b, 0x59, 0xcd, 0xaf, 0xf7, 0xd4, 0xeb, 0x72, 0x9b, 0x12,
	0xc1, 0xaf, 0xe1, 0x81, 0x3a, 0x7a, 0xbf, 0x97, 0xe5, 0x1d, 0xf4, 0x0a, 0x7d, 0x15, 0xc3, 0x67,
	0x50, 0xe7, 0xd6, 0xad, 0x17, 0x45, 0x80, 0x91, 0x62, 0xce, 0xcf, 0x31, 0xb9, 0x64, 0x63, 0xc3,
	0x58, 0x93, 0x0b, 0x8e, 0xb9, 0xc1, 0x01, 0xac, 0x1e, 0x12, 0x56, 0xba, 0x93, 0xeb, 0x79, 0x03,
	0xef, 0xc3, 0x27, 0x0a, 0x84, 0xe6, 0xbe, 0x1b, 0x2f, 0x73, 0x51, 0x2c, 0x3f, 0x41, 0xaf, 0xd0,
	0x57, 0xb1, 0x3c, 0x83, 0x66, 0xce, 0xb7, 0xd5, 0xab, 0x7c, 0x9b, 0x6f, 0x5e, 0x1f, 0x94, 0x7c,
	0x3f, 0x75, 0xe7, 0xdc, 0x0f, 0xdd, 0x8f, 0x22, 0x48, 0xa3, 0x33, 0xb2, 0xdb, 0x65, 0x67, 0xa1,
	0xb1, 0xb7, 0xd0, 0x51, 0x26, 0x8a, 0x3b, 0xe3, 0xfd, 0x64, 0xdd, 0x99, 0x68, 0x3f, 0x29, 0xbe,
	0x3e, 0xbc, 0x2f, 0xa0, 0x79, 0x10, 0xcd, 0xc8, 0x71, 0x90, 0x32, 0xc1, 0x20, 0x34, 0x66, 0xbc,
	0x44, 0x39, 0x92, 0xf6, 0x50, 0x2f, 0xf1, 0x08, 0xda, 0xa3, 0x64, 0x46, 0x83, 0xf0, 0x84, 0x05,
	0xec, 0x3c, 0x33, 0xd9, 0xa9, 0x6a, 0xb1, 0xd3, 0x36, 0x34, 0x32, 0x71, 0x44, 0x38, 0xea, 0x0e,
	0xd6, 0xc4, 0x53, 0x6b, 0xa8, 0xee, 0xd1, 0x90, 0x0c, 0xd5, 0x99, 0xaf, 0x5e, 0x42, 0xaf, 0xbc,
	0x87, 0x56, 0xc0, 0x1b, 0xc5, 0x67, 0x31, 0xbd, 0x88, 0x7b, 0x15, 0xd4, 0x00, 0xe7, 0xdd, 0x59,
	0xaf, 0x8a, 0x00, 0x1a, 0x07, 0x41, 0x34, 0x23, 0x61, 0xcf, 0x19, 0x50, 0xf0, 0x76, 0xcf, 0xd9,
	0xaf, 0x27, 0x1f, 0x26, 0xe8, 0x6b, 0x68, 0xc8, 0x01, 0x1f, 0xad, 0x72, 0x3f, 0xd6, 0xef, 0x85,
	0x3e, 0x32, 0x45, 0x32, 0x55, 0xb8, 0xa2, 0x55, 0x46, 0x49, 0xa1, 0x92, 0x4f, 0xf6, 0x8b, 0x55,
	0x06, 0xff, 0x3a, 0xe0, 0xf1, 0xf1, 0x80, 0x7b, 0x7c, 0x01, 0x50, 0x0c, 0x9c, 0xe8, 0x91, 0xa8,
	0xa7, 0xf2, 0x00, 0xda, 0xcf, 0xe7, 0x0b, 0x5c, 0x41, 0xcf, 0xc1, 0x53, 0xd3, 0x22, 0x12, 0xd6,
	0xed, 0xd1, 0xd1, 0x3a, 0xba, 0x07, 0x6d, 0x73, 0xd2, 0x43, 0xeb, 0xea, 0x7c, 0x79, 0x7e, 0xec,
	0xfb, 0x57, 0x37, 0xf2, 0xf8, 0x4c, 0x23, 0x51, 0x3c, 0x2d, 0x19, 0x29, 0x06, 0xc0, 0x92, 0x11,
	0x63, 0xaa, 0xc3, 0x15, 0xf4, 0x0a, 0xda, 0x32, 0x2a, 0xb9, 0x29, 0x53, 0x65, 0x4d, 0x70, 0x32,
	0x55, 0xf6, 0x34, 0x26, 0x15, 0x87, 0x64, 0x4e, 0x3f, 0xdc, 0x55, 0x71, 0xf0, 0x57, 0x1d, 0x3c,
	0xde, 0x63, 0x56, 0x8e, 0xc5, 0x28, 0x66, 0xe4, 0xd8, 0x60, 0xc5, 0x7e, 0xce, 0x4c, 0xc2, 0x6b,
	0xd7, 0x7e, 0xdf, 0xd0, 0x86, 0xad, 0x64, 0x3c, 0x46, 0x96, 0xe2, 0x01, 0x74, 0x2c, 0x2a, 0x47,
	0x7e, 0xa1, 0x67, 0xd3, 0x58, 0x7f, 0x63, 0xc1, 0x4e, 0x1e, 0xf6, 0xf7, 0xfa, 0x69, 0x37, 0x5a,
	0x1c, 0x3d, 0xbe, 0xa2, 0xb1, 0x0c, 0x86, 0xac, 0x11, 0x11, 0xad, 0xae, 0x91, 0x65, 0xa1, 0x7e,
	0x0b, 0xc0, 0x77, 0x53, 0xca, 0xfb, 0x0d, 0x3d, 0x34, 0x4e, 0xe7, 0xd5, 0xb1, 0x66, 0x0b, 0x73,
	0x90, 0xdf, 0x08, 0x2f, 0x07, 0x84, 0x84, 0x77, 0xd3, 0xfb, 0x4e, 0x54, 0x54, 0x4e, 0x80, 0x79,
	0x45, 0x95, 0x29, 0xb1, 0xbf, 0xaa, 0x89, 0xc7, 0xd4, 0xde, 0xcf, 0x1f, 0xa9, 0x7c, 0xb6, 0xed,
	0x1b, 0x06, 0x4a, 0xa4, 0x2f, 0x41, 0x94, 0x99, 0x1c, 0x57, 0xd0, 0x1b, 0x61, 0xc6, 0x64, 0xd0,
	0xdc, 0xcc, 0x02, 0x5a, 0x5d, 0x0c, 0x65, 0x20, 0x72, 0xa7, 0xaf, 0xfa, 0x91, 0xad, 0xae, 0x35,
	0xcd, 0x27, 0x02, 0x57, 0x06, 0xaf, 0xc0, 0xe3, 0xf4, 0xc8, 0xcb, 0x72, 0x1b, 0x1a, 0x92, 0xac,
	0x50, 0x5b, 0x94, 0xb0, 0x62, 0xcd, 0x7e, 0xaf, 0x4c, 0x71, 0xb8, 0xb2, 0x55, 0x3d, 0x6d, 0x88,
	0x7f, 0x32, 0x5e, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xad, 0x08, 0x2c, 0xf7, 0xd9, 0x10, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthSvcClient is the client API for AuthSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthSvcClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type authSvcClient struct {
	cc *grpc.ClientConn
}

func NewAuthSvcClient(cc *grpc.ClientConn) AuthSvcClient {
	return &authSvcClient{cc}
}

func (c *authSvcClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthSvc/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthSvc/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSvcServer is the server API for AuthSvc service.
type AuthSvcServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignUp(context.Context, *SignUpRequest) (*SignInResponse, error)
}

// UnimplementedAuthSvcServer can be embedded to have forward compatible implementations.
type UnimplementedAuthSvcServer struct {
}

func (*UnimplementedAuthSvcServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthSvcServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterAuthSvcServer(s *grpc.Server, srv AuthSvcServer) {
	s.RegisterService(&_AuthSvc_serviceDesc, srv)
}

func _AuthSvc_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthSvc/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthSvc/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthSvc",
	HandlerType: (*AuthSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AuthSvc_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AuthSvc_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
	GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
	CreateFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	RemoveFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	out := new(GetFollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/GetFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) CreateFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/CreateFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) RemoveFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, "/pb.UserSvc/RemoveFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error)
	CreateFollow(context.Context, *FollowRequest) (*FollowResponse, error)
	RemoveFollow(context.Context, *FollowRequest) (*FollowResponse, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserSvcServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserSvcServer) GetFollowers(ctx context.Context, req *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (*UnimplementedUserSvcServer) GetFollowing(ctx context.Context, req *GetFollowingRequest) (*GetFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}
func (*UnimplementedUserSvcServer) CreateFollow(ctx context.Context, req *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFollow not implemented")
}
func (*UnimplementedUserSvcServer) RemoveFollow(ctx context.Context, req *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFollow not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/GetFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).GetFollowing(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_CreateFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).CreateFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/CreateFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).CreateFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_RemoveFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).RemoveFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserSvc/RemoveFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).RemoveFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserSvc_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserSvc_GetUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _UserSvc_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _UserSvc_GetFollowing_Handler,
		},
		{
			MethodName: "CreateFollow",
			Handler:    _UserSvc_CreateFollow_Handler,
		},
		{
			MethodName: "RemoveFollow",
			Handler:    _UserSvc_RemoveFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// PostSvcClient is the client API for PostSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostSvcClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error)
	CreatePostLike(ctx context.Context, in *CreatePostLikeRequest, opts ...grpc.CallOption) (*Post, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	CreateCommentLike(ctx context.Context, in *CreateCommentLikeRequest, opts ...grpc.CallOption) (*Post, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	GetProfile(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	GetFeed(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error)
	GetPostLikes(ctx context.Context, in *GetPostLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetPostComments(ctx context.Context, in *GetPostCommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	GetCommentLikes(ctx context.Context, in *GetCommentLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error)
}

type postSvcClient struct {
	cc *grpc.ClientConn
}

func NewPostSvcClient(cc *grpc.ClientConn) PostSvcClient {
	return &postSvcClient{cc}
}

func (c *postSvcClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreatePostLike(ctx context.Context, in *CreatePostLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreatePostLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) CreateCommentLike(ctx context.Context, in *CreateCommentLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/CreateCommentLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetProfile(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetFeed(ctx context.Context, in *GetPostsRequest, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetPostLikes(ctx context.Context, in *GetPostLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetPostLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetPostComments(ctx context.Context, in *GetPostCommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetPostComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetCommentLikes(ctx context.Context, in *GetCommentLikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetCommentLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postSvcClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/pb.PostSvc/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSvcServer is the server API for PostSvc service.
type PostSvcServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*Post, error)
	CreatePostLike(context.Context, *CreatePostLikeRequest) (*Post, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	CreateCommentLike(context.Context, *CreateCommentLikeRequest) (*Post, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	GetProfile(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	GetFeed(context.Context, *GetPostsRequest) (*GetPostsResponse, error)
	GetPostLikes(context.Context, *GetPostLikesRequest) (*LikesResponse, error)
	GetPostComments(context.Context, *GetPostCommentsRequest) (*CommentsResponse, error)
	GetCommentLikes(context.Context, *GetCommentLikesRequest) (*LikesResponse, error)
	GetComment(context.Context, *GetCommentRequest) (*Comment, error)
}

// UnimplementedPostSvcServer can be embedded to have forward compatible implementations.
type UnimplementedPostSvcServer struct {
}

func (*UnimplementedPostSvcServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostSvcServer) CreatePostLike(ctx context.Context, req *CreatePostLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePostLike not implemented")
}
func (*UnimplementedPostSvcServer) CreateComment(ctx context.Context, req *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedPostSvcServer) CreateCommentLike(ctx context.Context, req *CreateCommentLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommentLike not implemented")
}
func (*UnimplementedPostSvcServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostSvcServer) GetProfile(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedPostSvcServer) GetFeed(ctx context.Context, req *GetPostsRequest) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (*UnimplementedPostSvcServer) GetPostLikes(ctx context.Context, req *GetPostLikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikes not implemented")
}
func (*UnimplementedPostSvcServer) GetPostComments(ctx context.Context, req *GetPostCommentsRequest) (*CommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostComments not implemented")
}
func (*UnimplementedPostSvcServer) GetCommentLikes(ctx context.Context, req *GetCommentLikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentLikes not implemented")
}
func (*UnimplementedPostSvcServer) GetComment(ctx context.Context, req *GetCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}

func RegisterPostSvcServer(s *grpc.Server, srv PostSvcServer) {
	s.RegisterService(&_PostSvc_serviceDesc, srv)
}

func _PostSvc_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreatePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreatePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreatePostLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreatePostLike(ctx, req.(*CreatePostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_CreateCommentLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).CreateCommentLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/CreateCommentLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).CreateCommentLike(ctx, req.(*CreateCommentLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetProfile(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetFeed(ctx, req.(*GetPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetPostLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetPostLikes(ctx, req.(*GetPostLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetPostComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetPostComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetPostComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetPostComments(ctx, req.(*GetPostCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetCommentLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetCommentLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetCommentLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetCommentLikes(ctx, req.(*GetCommentLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostSvc_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSvcServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostSvc/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSvcServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostSvc",
	HandlerType: (*PostSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostSvc_CreatePost_Handler,
		},
		{
			MethodName: "CreatePostLike",
			Handler:    _PostSvc_CreatePostLike_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostSvc_CreateComment_Handler,
		},
		{
			MethodName: "CreateCommentLike",
			Handler:    _PostSvc_CreateCommentLike_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostSvc_GetPost_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _PostSvc_GetProfile_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _PostSvc_GetFeed_Handler,
		},
		{
			MethodName: "GetPostLikes",
			Handler:    _PostSvc_GetPostLikes_Handler,
		},
		{
			MethodName: "GetPostComments",
			Handler:    _PostSvc_GetPostComments_Handler,
		},
		{
			MethodName: "GetCommentLikes",
			Handler:    _PostSvc_GetCommentLikes_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _PostSvc_GetComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// FileSvcClient is the client API for FileSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileSvcClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (FileSvc_UploadClient, error)
}

type fileSvcClient struct {
	cc *grpc.ClientConn
}

func NewFileSvcClient(cc *grpc.ClientConn) FileSvcClient {
	return &fileSvcClient{cc}
}

func (c *fileSvcClient) Upload(ctx context.Context, opts ...grpc.CallOption) (FileSvc_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileSvc_serviceDesc.Streams[0], "/pb.FileSvc/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileSvcUploadClient{stream}
	return x, nil
}

type FileSvc_UploadClient interface {
	Send(*FilePart) error
	CloseAndRecv() (*UploadStatus, error)
	grpc.ClientStream
}

type fileSvcUploadClient struct {
	grpc.ClientStream
}

func (x *fileSvcUploadClient) Send(m *FilePart) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileSvcUploadClient) CloseAndRecv() (*UploadStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileSvcServer is the server API for FileSvc service.
type FileSvcServer interface {
	Upload(FileSvc_UploadServer) error
}

// UnimplementedFileSvcServer can be embedded to have forward compatible implementations.
type UnimplementedFileSvcServer struct {
}

func (*UnimplementedFileSvcServer) Upload(srv FileSvc_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterFileSvcServer(s *grpc.Server, srv FileSvcServer) {
	s.RegisterService(&_FileSvc_serviceDesc, srv)
}

func _FileSvc_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileSvcServer).Upload(&fileSvcUploadServer{stream})
}

type FileSvc_UploadServer interface {
	SendAndClose(*UploadStatus) error
	Recv() (*FilePart, error)
	grpc.ServerStream
}

type fileSvcUploadServer struct {
	grpc.ServerStream
}

func (x *fileSvcUploadServer) SendAndClose(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileSvcUploadServer) Recv() (*FilePart, error) {
	m := new(FilePart)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FileSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileSvc",
	HandlerType: (*FileSvcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FileSvc_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "portal.proto",
}
