// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignInResponse) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type SignUpRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{2}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowerCount        uint32   `protobuf:"varint,2,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,3,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	ProfilePicture       []byte   `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3" json:"profile_picture,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	PostCount            uint32   `protobuf:"varint,8,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *User) GetProfilePicture() []byte {
	if m != nil {
		return m.ProfilePicture
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *User) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FollowersRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowersRequest) Reset()         { *m = FollowersRequest{} }
func (m *FollowersRequest) String() string { return proto.CompactTextString(m) }
func (*FollowersRequest) ProtoMessage()    {}
func (*FollowersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{6}
}

func (m *FollowersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowersRequest.Unmarshal(m, b)
}
func (m *FollowersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowersRequest.Marshal(b, m, deterministic)
}
func (m *FollowersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowersRequest.Merge(m, src)
}
func (m *FollowersRequest) XXX_Size() int {
	return xxx_messageInfo_FollowersRequest.Size(m)
}
func (m *FollowersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowersRequest proto.InternalMessageInfo

func (m *FollowersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FollowersRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type FollowersResponse struct {
	Followers            []*User  `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowersResponse) Reset()         { *m = FollowersResponse{} }
func (m *FollowersResponse) String() string { return proto.CompactTextString(m) }
func (*FollowersResponse) ProtoMessage()    {}
func (*FollowersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{7}
}

func (m *FollowersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowersResponse.Unmarshal(m, b)
}
func (m *FollowersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowersResponse.Marshal(b, m, deterministic)
}
func (m *FollowersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowersResponse.Merge(m, src)
}
func (m *FollowersResponse) XXX_Size() int {
	return xxx_messageInfo_FollowersResponse.Size(m)
}
func (m *FollowersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowersResponse proto.InternalMessageInfo

func (m *FollowersResponse) GetFollowers() []*User {
	if m != nil {
		return m.Followers
	}
	return nil
}

type FollowingRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowingRequest) Reset()         { *m = FollowingRequest{} }
func (m *FollowingRequest) String() string { return proto.CompactTextString(m) }
func (*FollowingRequest) ProtoMessage()    {}
func (*FollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{8}
}

func (m *FollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingRequest.Unmarshal(m, b)
}
func (m *FollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingRequest.Marshal(b, m, deterministic)
}
func (m *FollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingRequest.Merge(m, src)
}
func (m *FollowingRequest) XXX_Size() int {
	return xxx_messageInfo_FollowingRequest.Size(m)
}
func (m *FollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingRequest proto.InternalMessageInfo

func (m *FollowingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FollowingRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type FollowingResponse struct {
	Following            []*User  `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowingResponse) Reset()         { *m = FollowingResponse{} }
func (m *FollowingResponse) String() string { return proto.CompactTextString(m) }
func (*FollowingResponse) ProtoMessage()    {}
func (*FollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{9}
}

func (m *FollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowingResponse.Unmarshal(m, b)
}
func (m *FollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowingResponse.Marshal(b, m, deterministic)
}
func (m *FollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowingResponse.Merge(m, src)
}
func (m *FollowingResponse) XXX_Size() int {
	return xxx_messageInfo_FollowingResponse.Size(m)
}
func (m *FollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowingResponse proto.InternalMessageInfo

func (m *FollowingResponse) GetFollowing() []*User {
	if m != nil {
		return m.Following
	}
	return nil
}

type Post struct {
	PostId               string     `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte     `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	LikeCount            uint32     `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	TopComments          []*Comment `protobuf:"bytes,4,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	CommentCount         uint32     `protobuf:"varint,5,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	UserId               string     `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string     `protobuf:"bytes,7,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAtSeconds     uint32     `protobuf:"fixed32,8,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{10}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *Post) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *Post) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Post) GetTopComments() []*Comment {
	if m != nil {
		return m.TopComments
	}
	return nil
}

func (m *Post) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Post) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Comment struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LikeCount            uint32   `protobuf:"varint,4,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,5,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{11}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Comment) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Comment) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type Like struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAtSeconds     uint32   `protobuf:"fixed32,2,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Like) Reset()         { *m = Like{} }
func (m *Like) String() string { return proto.CompactTextString(m) }
func (*Like) ProtoMessage()    {}
func (*Like) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{12}
}

func (m *Like) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Like.Unmarshal(m, b)
}
func (m *Like) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Like.Marshal(b, m, deterministic)
}
func (m *Like) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Like.Merge(m, src)
}
func (m *Like) XXX_Size() int {
	return xxx_messageInfo_Like.Size(m)
}
func (m *Like) XXX_DiscardUnknown() {
	xxx_messageInfo_Like.DiscardUnknown(m)
}

var xxx_messageInfo_Like proto.InternalMessageInfo

func (m *Like) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Like) GetCreatedAtSeconds() uint32 {
	if m != nil {
		return m.CreatedAtSeconds
	}
	return 0
}

type CreatePostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{13}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type CreateLikeRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLikeRequest) Reset()         { *m = CreateLikeRequest{} }
func (m *CreateLikeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLikeRequest) ProtoMessage()    {}
func (*CreateLikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{14}
}

func (m *CreateLikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLikeRequest.Unmarshal(m, b)
}
func (m *CreateLikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLikeRequest.Marshal(b, m, deterministic)
}
func (m *CreateLikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLikeRequest.Merge(m, src)
}
func (m *CreateLikeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLikeRequest.Size(m)
}
func (m *CreateLikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLikeRequest proto.InternalMessageInfo

func (m *CreateLikeRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreateLikeRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreateLikeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateLikeRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type CreateCommentRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Picture              []byte   `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{15}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreateCommentRequest) GetPicture() []byte {
	if m != nil {
		return m.Picture
	}
	return nil
}

func (m *CreateCommentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

type GetPostRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{16}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type GetFeedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedRequest) Reset()         { *m = GetFeedRequest{} }
func (m *GetFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedRequest) ProtoMessage()    {}
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{17}
}

func (m *GetFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedRequest.Unmarshal(m, b)
}
func (m *GetFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedRequest.Merge(m, src)
}
func (m *GetFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedRequest.Size(m)
}
func (m *GetFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedRequest proto.InternalMessageInfo

func (m *GetFeedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetFeedRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetFeedResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedResponse) Reset()         { *m = GetFeedResponse{} }
func (m *GetFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedResponse) ProtoMessage()    {}
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{18}
}

func (m *GetFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedResponse.Unmarshal(m, b)
}
func (m *GetFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedResponse.Merge(m, src)
}
func (m *GetFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedResponse.Size(m)
}
func (m *GetFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedResponse proto.InternalMessageInfo

func (m *GetFeedResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type CommentsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsRequest) Reset()         { *m = CommentsRequest{} }
func (m *CommentsRequest) String() string { return proto.CompactTextString(m) }
func (*CommentsRequest) ProtoMessage()    {}
func (*CommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{19}
}

func (m *CommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsRequest.Unmarshal(m, b)
}
func (m *CommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsRequest.Marshal(b, m, deterministic)
}
func (m *CommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsRequest.Merge(m, src)
}
func (m *CommentsRequest) XXX_Size() int {
	return xxx_messageInfo_CommentsRequest.Size(m)
}
func (m *CommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsRequest proto.InternalMessageInfo

func (m *CommentsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CommentsRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CommentsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentsResponse) Reset()         { *m = CommentsResponse{} }
func (m *CommentsResponse) String() string { return proto.CompactTextString(m) }
func (*CommentsResponse) ProtoMessage()    {}
func (*CommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{20}
}

func (m *CommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentsResponse.Unmarshal(m, b)
}
func (m *CommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentsResponse.Marshal(b, m, deterministic)
}
func (m *CommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentsResponse.Merge(m, src)
}
func (m *CommentsResponse) XXX_Size() int {
	return xxx_messageInfo_CommentsResponse.Size(m)
}
func (m *CommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentsResponse proto.InternalMessageInfo

func (m *CommentsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type LikesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikesRequest) Reset()         { *m = LikesRequest{} }
func (m *LikesRequest) String() string { return proto.CompactTextString(m) }
func (*LikesRequest) ProtoMessage()    {}
func (*LikesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{21}
}

func (m *LikesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikesRequest.Unmarshal(m, b)
}
func (m *LikesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikesRequest.Marshal(b, m, deterministic)
}
func (m *LikesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesRequest.Merge(m, src)
}
func (m *LikesRequest) XXX_Size() int {
	return xxx_messageInfo_LikesRequest.Size(m)
}
func (m *LikesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikesRequest proto.InternalMessageInfo

func (m *LikesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LikesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type LikesResponse struct {
	Likes                []*Like  `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikesResponse) Reset()         { *m = LikesResponse{} }
func (m *LikesResponse) String() string { return proto.CompactTextString(m) }
func (*LikesResponse) ProtoMessage()    {}
func (*LikesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ead6f188e0e8e0b1, []int{22}
}

func (m *LikesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikesResponse.Unmarshal(m, b)
}
func (m *LikesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikesResponse.Marshal(b, m, deterministic)
}
func (m *LikesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikesResponse.Merge(m, src)
}
func (m *LikesResponse) XXX_Size() int {
	return xxx_messageInfo_LikesResponse.Size(m)
}
func (m *LikesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikesResponse proto.InternalMessageInfo

func (m *LikesResponse) GetLikes() []*Like {
	if m != nil {
		return m.Likes
	}
	return nil
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "pb.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "pb.SignInResponse")
	proto.RegisterType((*SignUpRequest)(nil), "pb.SignUpRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*FollowersRequest)(nil), "pb.FollowersRequest")
	proto.RegisterType((*FollowersResponse)(nil), "pb.FollowersResponse")
	proto.RegisterType((*FollowingRequest)(nil), "pb.FollowingRequest")
	proto.RegisterType((*FollowingResponse)(nil), "pb.FollowingResponse")
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Comment)(nil), "pb.Comment")
	proto.RegisterType((*Like)(nil), "pb.Like")
	proto.RegisterType((*CreatePostRequest)(nil), "pb.CreatePostRequest")
	proto.RegisterType((*CreateLikeRequest)(nil), "pb.CreateLikeRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "pb.CreateCommentRequest")
	proto.RegisterType((*GetPostRequest)(nil), "pb.GetPostRequest")
	proto.RegisterType((*GetFeedRequest)(nil), "pb.GetFeedRequest")
	proto.RegisterType((*GetFeedResponse)(nil), "pb.GetFeedResponse")
	proto.RegisterType((*CommentsRequest)(nil), "pb.CommentsRequest")
	proto.RegisterType((*CommentsResponse)(nil), "pb.CommentsResponse")
	proto.RegisterType((*LikesRequest)(nil), "pb.LikesRequest")
	proto.RegisterType((*LikesResponse)(nil), "pb.LikesResponse")
}

func init() { proto.RegisterFile("portal.proto", fileDescriptor_ead6f188e0e8e0b1) }

var fileDescriptor_ead6f188e0e8e0b1 = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xef, 0x8e, 0xdb, 0x44,
	0x10, 0xbf, 0x38, 0x4e, 0x9c, 0x8c, 0x93, 0xdc, 0xdd, 0xf6, 0x2a, 0x4c, 0x24, 0x50, 0x64, 0x04,
	0xa4, 0x12, 0xba, 0xaa, 0x29, 0x45, 0x08, 0x54, 0xd0, 0xe9, 0x50, 0xd1, 0x49, 0x20, 0x55, 0x39,
	0xdd, 0x17, 0xbe, 0x44, 0x3e, 0x7b, 0x1b, 0x56, 0x4d, 0xbc, 0xc6, 0xeb, 0x50, 0x21, 0xf1, 0x0c,
	0x3c, 0x0b, 0x2f, 0xc2, 0x73, 0xf0, 0x95, 0x47, 0x40, 0xfb, 0xd7, 0xbb, 0x6e, 0x5c, 0x42, 0x2b,
	0xdd, 0xb7, 0xec, 0xec, 0xfc, 0x66, 0x7e, 0x3b, 0xf3, 0xdb, 0x59, 0x07, 0x46, 0x05, 0x2d, 0xab,
	0x64, 0x73, 0x5e, 0x94, 0xb4, 0xa2, 0xc8, 0x2b, 0x6e, 0xe3, 0x0b, 0x18, 0x5f, 0x93, 0x75, 0x7e,
	0x95, 0x2f, 0xf1, 0x2f, 0x3b, 0xcc, 0x2a, 0x74, 0x06, 0x3d, 0xbc, 0x4d, 0xc8, 0x26, 0xea, 0xcc,
	0x3a, 0xf3, 0xe1, 0x52, 0x2e, 0xd0, 0x14, 0x06, 0x45, 0xc2, 0xd8, 0x2b, 0x5a, 0x66, 0x91, 0x27,
	0x36, 0xcc, 0x3a, 0xfe, 0x0e, 0x26, 0x3a, 0x04, 0x2b, 0x68, 0xce, 0x30, 0x7a, 0x0f, 0x82, 0x1d,
	0xc3, 0xe5, 0x8a, 0x64, 0x2a, 0x4a, 0x9f, 0x2f, 0xaf, 0x32, 0xf4, 0x3e, 0x0c, 0x08, 0x5b, 0x25,
	0xd9, 0x96, 0xe4, 0x51, 0x77, 0xd6, 0x99, 0x0f, 0x96, 0x01, 0x61, 0x17, 0x7c, 0x19, 0xff, 0x24,
	0x89, 0xdc, 0x14, 0x6f, 0x26, 0x62, 0x85, 0xf6, 0x9c, 0xd0, 0x36, 0xc3, 0x6e, 0x83, 0xe1, 0x5f,
	0x1e, 0xf8, 0x37, 0x0c, 0x97, 0xed, 0xc4, 0x3e, 0x86, 0xc9, 0x0b, 0xba, 0xd9, 0xd0, 0x57, 0xb8,
	0x5c, 0xa5, 0x74, 0x97, 0x57, 0x22, 0xfa, 0x78, 0x39, 0xd6, 0xd6, 0x4b, 0x6e, 0x44, 0x9f, 0xc2,
	0xb1, 0x34, 0x90, 0x7c, 0xad, 0xfc, 0xba, 0xc2, 0x6f, 0x62, 0xcc, 0xc6, 0xb1, 0x28, 0xe9, 0x0b,
	0xb2, 0xc1, 0xab, 0x82, 0xa4, 0xd5, 0xae, 0xc4, 0x91, 0x3f, 0xeb, 0xcc, 0x47, 0xcb, 0x89, 0x32,
	0x3f, 0x97, 0x56, 0x84, 0xc0, 0xcf, 0x93, 0x2d, 0x8e, 0x7a, 0x82, 0x8e, 0xf8, 0x8d, 0x66, 0x10,
	0x66, 0x98, 0xa5, 0x25, 0x29, 0x2a, 0x42, 0xf3, 0xa8, 0x2f, 0xb6, 0x6c, 0x13, 0x3f, 0x2c, 0x27,
	0x2e, 0x90, 0x81, 0x3c, 0xac, 0x5e, 0xa3, 0x0f, 0x00, 0x0a, 0xca, 0x2a, 0x45, 0x6f, 0x20, 0xe8,
	0x0d, 0xb9, 0x45, 0x32, 0xfb, 0x0c, 0x50, 0x5a, 0xe2, 0xa4, 0xc2, 0xd9, 0x2a, 0xa9, 0x56, 0x0c,
	0xa7, 0x34, 0xcf, 0x58, 0x34, 0x9c, 0x75, 0xe6, 0xc1, 0xf2, 0x44, 0xed, 0x5c, 0x54, 0xd7, 0xd2,
	0x5e, 0x37, 0x01, 0xac, 0x26, 0xc4, 0x25, 0x9c, 0x5e, 0x0a, 0x4f, 0x5e, 0x54, 0xdd, 0xaf, 0xd6,
	0xda, 0xda, 0x64, 0xbd, 0x06, 0x59, 0x13, 0xbf, 0x6b, 0x37, 0x59, 0x17, 0xc5, 0xaf, 0x8b, 0x12,
	0x3f, 0x80, 0xc9, 0xf7, 0xb8, 0x3a, 0x24, 0x61, 0xfc, 0x2d, 0x9c, 0x3c, 0x53, 0x6d, 0x63, 0xff,
	0xc9, 0x0e, 0x81, 0x5f, 0x24, 0x6b, 0xac, 0xfa, 0x2d, 0x7e, 0xc7, 0x5f, 0xc3, 0xa9, 0x15, 0x40,
	0x89, 0xfa, 0x13, 0x18, 0x6a, 0x31, 0xb0, 0xa8, 0x33, 0xeb, 0xce, 0xc3, 0xc5, 0xe0, 0xbc, 0xb8,
	0x3d, 0x17, 0x94, 0xea, 0xad, 0x3a, 0x3b, 0xc9, 0xd7, 0xef, 0x96, 0x5d, 0x04, 0x68, 0x66, 0x27,
	0xf9, 0xba, 0x2d, 0x3b, 0xc9, 0xd7, 0xf1, 0x1f, 0x1e, 0xf8, 0xcf, 0xa9, 0x4c, 0x29, 0x64, 0x50,
	0xa7, 0xe4, 0xcb, 0xab, 0x0c, 0x45, 0x10, 0x68, 0x49, 0x7a, 0x42, 0x92, 0x7a, 0xc9, 0x95, 0xb3,
	0x21, 0x2f, 0xb1, 0x23, 0xec, 0x21, 0xb7, 0x48, 0xe5, 0x9c, 0xc3, 0xa8, 0xa2, 0xc5, 0x2a, 0xa5,
	0xdb, 0x2d, 0xce, 0x2b, 0x16, 0xf9, 0x82, 0x45, 0xc8, 0x59, 0x5c, 0x4a, 0xdb, 0x32, 0xac, 0x68,
	0xa1, 0x7e, 0x33, 0xf4, 0x11, 0x8c, 0x95, 0xaf, 0x8a, 0xd8, 0x13, 0x11, 0x47, 0xca, 0x28, 0x83,
	0x5a, 0x95, 0xe9, 0x3b, 0x95, 0x89, 0x20, 0x48, 0x13, 0x79, 0x01, 0xa4, 0xc2, 0xf5, 0xb2, 0x45,
	0xc1, 0x83, 0xfd, 0x0a, 0x8e, 0xff, 0xec, 0x40, 0xa0, 0x28, 0xf1, 0x03, 0x6a, 0x46, 0xa6, 0x2c,
	0x43, 0x65, 0xb9, 0xca, 0xda, 0x67, 0x4b, 0xe3, 0x42, 0x76, 0x5f, 0xbf, 0x90, 0x6e, 0xe9, 0xfc,
	0x66, 0xe9, 0xf6, 0x53, 0xee, 0xb5, 0x50, 0xfe, 0x11, 0xfc, 0x1f, 0xc8, 0xcb, 0x37, 0x8c, 0xd1,
	0xfd, 0xe1, 0xbc, 0x96, 0x70, 0xbf, 0xe9, 0xdb, 0xca, 0x75, 0x61, 0x29, 0xf2, 0xff, 0xca, 0xc3,
	0xa2, 0xd3, 0x6d, 0x6b, 0x95, 0xef, 0xb4, 0xaa, 0x4e, 0xcd, 0xcf, 0x73, 0xb7, 0xa9, 0x7f, 0x87,
	0x33, 0x99, 0x5a, 0x6b, 0xf3, 0x4e, 0xb3, 0xcb, 0x69, 0x75, 0x48, 0xc1, 0xe3, 0xa7, 0xc2, 0xf5,
	0x19, 0xc6, 0xd9, 0x5b, 0x4d, 0x8b, 0x47, 0x70, 0x6c, 0xe0, 0x6a, 0x56, 0x7c, 0x08, 0x3d, 0x1e,
	0xdb, 0x99, 0x52, 0x82, 0x8a, 0x34, 0xc7, 0xdf, 0xc0, 0xb1, 0xbe, 0xa4, 0x6f, 0x95, 0x72, 0x01,
	0x27, 0x35, 0xfe, 0xc0, 0x9c, 0x0b, 0x18, 0x71, 0x0d, 0x98, 0x84, 0x13, 0xf0, 0x4c, 0x2e, 0x8f,
	0xec, 0xcf, 0xf3, 0x10, 0xc6, 0x0a, 0x53, 0x27, 0xe1, 0x77, 0xca, 0x49, 0x22, 0x94, 0x25, 0xcd,
	0x0b, 0x06, 0xe1, 0xc5, 0xae, 0xfa, 0xf9, 0x1a, 0x97, 0xbf, 0x92, 0x14, 0xa3, 0x47, 0xd0, 0x97,
	0x1f, 0x26, 0xe8, 0x94, 0x7b, 0x3a, 0xdf, 0x39, 0x53, 0x64, 0x9b, 0x64, 0xfc, 0xf8, 0x48, 0x43,
	0x6e, 0x8a, 0x1a, 0x62, 0xbe, 0x48, 0xf6, 0x43, 0x16, 0x7f, 0x77, 0x20, 0xe4, 0x53, 0x58, 0x67,
	0x7d, 0x08, 0x50, 0x3f, 0x8e, 0xe8, 0xbe, 0x18, 0x8f, 0xcd, 0xc7, 0x72, 0x6a, 0x66, 0x77, 0x7c,
	0x84, 0x1e, 0x40, 0xa0, 0x5e, 0x36, 0x24, 0x32, 0xb8, 0xcf, 0x9c, 0xe3, 0xfa, 0x14, 0x46, 0xbc,
	0xd9, 0xfa, 0xad, 0x41, 0x67, 0x7c, 0xaf, 0xf9, 0xd6, 0x4d, 0xef, 0x37, 0xac, 0xe6, 0x74, 0x36,
	0x9c, 0xe4, 0x6b, 0x1b, 0x5e, 0x3f, 0x56, 0x36, 0xdc, 0x7a, 0x81, 0xe2, 0xa3, 0xc5, 0x3f, 0x5d,
	0x08, 0x79, 0x4f, 0x5f, 0x3b, 0xa9, 0x78, 0x70, 0xac, 0x93, 0x5a, 0xba, 0x9f, 0x1a, 0x25, 0xc4,
	0x47, 0xe8, 0x31, 0x4c, 0x6a, 0x07, 0x31, 0xe2, 0x2c, 0x90, 0x35, 0x22, 0x1c, 0xd0, 0x17, 0x7a,
	0x86, 0x28, 0xcd, 0x1d, 0x8a, 0x7b, 0x02, 0x63, 0x07, 0x87, 0xa2, 0x1a, 0xe3, 0xce, 0x04, 0x07,
	0x26, 0xbb, 0x21, 0x4e, 0xa4, 0xbb, 0xd1, 0x76, 0x9c, 0xcf, 0x85, 0x2b, 0xbf, 0x7a, 0xc6, 0xd5,
	0xba, 0xc6, 0xd3, 0x7b, 0x8e, 0xcd, 0x34, 0xe1, 0x89, 0x68, 0x82, 0xae, 0x00, 0x43, 0x27, 0x5a,
	0xc5, 0xa6, 0x7f, 0xa7, 0x96, 0xc5, 0xc0, 0xbe, 0x14, 0xf7, 0xdc, 0xaa, 0xc1, 0xc1, 0xc8, 0xaf,
	0x20, 0xac, 0x91, 0x0c, 0xdd, 0xb3, 0x1e, 0x6c, 0x03, 0x3c, 0x73, 0x8d, 0x1a, 0x7b, 0xdb, 0x17,
	0xff, 0x14, 0x1e, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x37, 0xbd, 0x32, 0xbe, 0x39, 0x0c, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignUp(context.Context, *SignUpRequest) (*SignInResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AuthService_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AuthService_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	GetFollowers(ctx context.Context, in *FollowersRequest, opts ...grpc.CallOption) (*FollowersResponse, error)
	GetFollowing(ctx context.Context, in *FollowingRequest, opts ...grpc.CallOption) (*FollowingResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowers(ctx context.Context, in *FollowersRequest, opts ...grpc.CallOption) (*FollowersResponse, error) {
	out := new(FollowersResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/GetFollowers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFollowing(ctx context.Context, in *FollowingRequest, opts ...grpc.CallOption) (*FollowingResponse, error) {
	out := new(FollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/GetFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetFollowers(context.Context, *FollowersRequest) (*FollowersResponse, error)
	GetFollowing(context.Context, *FollowingRequest) (*FollowingResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) GetFollowers(ctx context.Context, req *FollowersRequest) (*FollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (*UnimplementedUserServiceServer) GetFollowing(ctx context.Context, req *FollowingRequest) (*FollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetFollowers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowers(ctx, req.(*FollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFollowing(ctx, req.(*FollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _UserService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _UserService_GetFollowing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error)
	CreatePostLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error)
	CreateCommentLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Post, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	GetPostLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetCommentLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreatePostLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostService/CreatePostLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateCommentLike(ctx context.Context, in *CreateLikeRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostService/CreateCommentLike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetPostLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetCommentLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetComments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	out := new(CommentsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*Post, error)
	CreatePostLike(context.Context, *CreateLikeRequest) (*Post, error)
	CreateCommentLike(context.Context, *CreateLikeRequest) (*Post, error)
	CreateComment(context.Context, *CreateCommentRequest) (*Post, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	GetPostLikes(context.Context, *LikesRequest) (*LikesResponse, error)
	GetCommentLikes(context.Context, *LikesRequest) (*LikesResponse, error)
	GetComments(context.Context, *CommentsRequest) (*CommentsResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) CreatePostLike(ctx context.Context, req *CreateLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePostLike not implemented")
}
func (*UnimplementedPostServiceServer) CreateCommentLike(ctx context.Context, req *CreateLikeRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommentLike not implemented")
}
func (*UnimplementedPostServiceServer) CreateComment(ctx context.Context, req *CreateCommentRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (*UnimplementedPostServiceServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostServiceServer) GetFeed(ctx context.Context, req *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (*UnimplementedPostServiceServer) GetPostLikes(ctx context.Context, req *LikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikes not implemented")
}
func (*UnimplementedPostServiceServer) GetCommentLikes(ctx context.Context, req *LikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentLikes not implemented")
}
func (*UnimplementedPostServiceServer) GetComments(ctx context.Context, req *CommentsRequest) (*CommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreatePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/CreatePostLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePostLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateCommentLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateCommentLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/CreateCommentLike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateCommentLike(ctx, req.(*CreateLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetPostLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostLikes(ctx, req.(*LikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetCommentLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentLikes(ctx, req.(*LikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetComments(ctx, req.(*CommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "CreatePostLike",
			Handler:    _PostService_CreatePostLike_Handler,
		},
		{
			MethodName: "CreateCommentLike",
			Handler:    _PostService_CreateCommentLike_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostService_CreateComment_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _PostService_GetFeed_Handler,
		},
		{
			MethodName: "GetPostLikes",
			Handler:    _PostService_GetPostLikes_Handler,
		},
		{
			MethodName: "GetCommentLikes",
			Handler:    _PostService_GetCommentLikes_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _PostService_GetComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal.proto",
}
